export interface PrayerType {
    id: number;             // bigint generated by default
    type: string | null;
    sequence: number | null;
    parent_type_id: number | null;
    subtypes: PrayerType[] | null;
    isEditing: boolean | null;
    tempTypeName: string | null;
  }
  