export interface SectionText {
    id: number;             // bigint generated by default
    created_at: string;     // timestamp with time zone
    liturgical_text_id: string | null;
    prayer_section_id: string | null;
    sequence: number;
    repetition: number | null;
    start_time: number | null;
    end_time: number | null;
  }
  