import { LiturgicalText } from "./liturgical-text.model";
import { TextElement } from "./text-element.model";

export interface SectionText {
    id: number;             // bigint generated by default
    created_at: string;     // timestamp with time zone
    liturgical_text_id: string | null;
    prayer_section_id: string | null;
    sequence: number;
    repetition: number | null;
    start_time: number | null;
    end_time: number | null;
    text?: LiturgicalText | null;
    italic: boolean;
    section_text_elements?: SectionTextElement[] | null;
  }
  

  export interface SectionTextElement {
    id?: string;
    section_text_id: number;
    text_element_id: string;
    start_time: number;
    end_time: number;
    text_element: TextElement;
    sequence: number;
  }